aryan/urls.py
from .views import *
from django.conf.urls import url
from django.urls import include,path

app_name = 'cv'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    path('teams', TeamView.as_view(), name='teams'),
    path('about',AboutView.as_view(),name='about'),
    path('rewards',RewardsView.as_view(),name='rewards'),
    path('blogs',BlogsView.as_view(),name='blogs'),
    path('blog/',BlogsingleView.as_view(),name='blog'),
    path('contact',ContactView.as_view(),name='contact'),
]

cv/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aryan.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import  User
from django.db.models.signals import post_save
from django.dispatch import receiver
from aryan.models import Teams, Winner
import os
import random

# def get_filename_ext(filepath):
#     base_name=os.path.basename(filepath)
#     name,ext=os.path.splitext(base_name)
#     return name,ext

# def user_image_path(instance, filename):
#     new_filename=random.randint(1,1234567890)
#     name,ext=get_filename_ext(filename)
#     final_filename='{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
#     return "userprofile/{final_filename}".format(
#         new_filename=new_filename,
#         final_filename=final_filename
#     )

# class Profile(models.Model):
#     STATUS_CHOICES=(
#     ('active','Active'),
#     ('in-active','In-active'),
#     )
#     user=models.OneToOneField(User,on_delete=models.CASCADE)
#     # name=models.CharField(max_length=30,unique=True)
#     address=models.CharField(max_length=40)
#     phone_no=models.IntegerField(null=True)
#     short_description=models.CharField(max_length=80, unique=True)
#     description=models.TextField(unique=True)
#     description2=models.TextField(unique=True,blank=True)
#     name_in_style= models.CharField(max_length=30, unique=True)
#     image1=models.ImageField(upload_to=user_image_path, null=True, blank=False)
#     fb_link=models.CharField(max_length=100, unique=True)
#     teams=models.ManyToManyField(Teams)
#     # winner=models.OneToOneField(Winner, on_delete=models.CASCADE)
#     rewards=models.ImageField(upload_to=user_image_path, null=True, blank=True)
#     # collection=models.ManyToManyField(Teams)

#     def __str__(self):
#         return self.user.username

# @receiver(post_save,sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()

aryan/models.py
from django.db import models
from django.conf import settings
import os
import random

def get_filename_ext(filepath):
    base_name=os.path.basename(filepath)
    name,ext=os.path.splitext(base_name)
    return name,ext

def user_image_path(instance, filename):
    new_filename=random.randint(1,1234567890)
    name,ext=get_filename_ext(filename)
    final_filename='{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
    return "company/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )

def winner_image_path(instance, filename):
    new_filename=random.randint(1,123456789)
    name, ext=get_filename_ext(filename)
    final_filename='{new_filename}{ext}'.format(new_filename=new_filename,ext=ext)
    return "winner/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )

class Teams(models.Model):
    ACTIVE_CHOICES=(
        ('yes','Yes'),
        ('no','No'),
    )
    # user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name=models.CharField(max_length=30, unique=True)
    teamname=models.CharField(max_length=30, unique=True)
    active=models.CharField(max_length=10,choices=ACTIVE_CHOICES,default='no')
    date=models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.name

class Company(models.Model):
    STATUS_CHOICES=(
    ('active','Active'),
    ('in-active','In-active'),
    )
    name=models.CharField(max_length=30,unique=True)
    address=models.CharField(max_length=40)
    phone_no=models.IntegerField(null=True)
    short_description=models.CharField(max_length=80, unique=True)
    description=models.TextField(unique=True)
    description2=models.TextField(unique=True,blank=True)
    name_in_style= models.CharField(max_length=30, unique=True)
    logo=models.ImageField(upload_to=user_image_path, null=True, blank=False)
    image1=models.ImageField(upload_to=user_image_path, null=True, blank=True)
    image2=models.ImageField(upload_to=user_image_path, null=True, blank=True)
    fb_link=models.CharField(max_length=100, unique=True)
    teams=models.ManyToManyField(Teams)
    # winner=models.OneToOneField(Winner, on_delete=models.CASCADE)
    rewards=models.ImageField(upload_to=user_image_path, null=True, blank=True)
    # collection=models.ManyToManyField(Teams)



class Gameweekwinner(models.Model):
    name=models.OneToOneField(Teams,on_delete=models.CASCADE)
    no=models.IntegerField(unique=True,blank=False)
    points=models.IntegerField(unique=True,blank=False)

    def __str__(self):
        return self.name.name

class Winner(models.Model):
    name=models.OneToOneField(Teams,on_delete=models.CASCADE)
    Year=models.IntegerField(unique=True,blank=False)
    image=models.ImageField(upload_to=winner_image_path,null=True,blank=False)
    points=models.IntegerField(unique=True,blank=False)
    voice=models.TextField(unique=True,blank=False)

    def __str__(self):
        return self.name.name

# class Collection(models.Model):
#     FEATURED_CHOICES=(
#         ('yes','Yes'),
#         ('no','No'),
#     )
#     # user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
#     name=models.CharField(max_length=30, unique=True)
#     short_description=models.CharField(max_length=80, unique=True)
#     image=models.ImageField(upload_to=users_image_path,null=True,blank=False)
#     featured=models.CharField(max_length=10,choices=FEATURED_CHOICES,default='no')
#     date=models.DateTimeField(auto_now_add=True,blank=True)

#     def __str__(self):
#         return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

aryan/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from .models import  Company,Teams,Gameweekwinner, Winner
from django.contrib.auth.models import User

class HomeView(TemplateView):
    template_name = 'index.html'

    def get(self, request):
        # company=Company.objects.filter(id=1)
        company=get_object_or_404(Company, id=1)
        gwwinner=Gameweekwinner.objects.all()
        winner=Winner.objects.all()

        args={
            'company':company,
            'gwwinner':gwwinner,
            'winner':winner
        }
        return render(request,self.template_name,args)

class TeamView(TemplateView):
    template_name='teams.html'

    def get(self,request):
        winner=Winner.objects.all()
        company=get_object_or_404(Company, id=1)
        teams=Teams.objects.all()
        args={
            'company':company,
            'teams':teams,
            'winner':winner
        }
        return render(request,self.template_name,args)

class AboutView(TemplateView):
    template_name='about.html'
    
    def get(self,request):
        company=get_object_or_404(Company, id=1)

        args={
            'company':company
        }
        return render(request,self.template_name,args)

class RewardsView(TemplateView):
    template_name='rewards.html'

    def get(self,request):
        company=get_object_or_404(Company, id=1)

        args={
            'company':company
        }
        return render(request,self.template_name,args)

class BlogsView(TemplateView):
    template_name='blog.html'

    def get(self,request):
        args={

        }
        return render(request,self.template_name,args)

class BlogsingleView(TemplateView):
    template_name='single.html'

    def get(self,request):
        args={

        }
        return render(request,self.template_name,args)


class ContactView(TemplateView):
    template_name='contact.html'

    def get(self,request):
        company=get_object_or_404(Company, id=1)

        args={
            'company':company
        }
        return render(request,self.template_name,args)

templates/about.html
{% extends 'base.html' %}
{% block title %}About me{% endblock %}
{% block stylesheet %} {% endblock%}

{% block content %}
{% include 'nav.html' %}

		<div id="colorlib-main">
			<section class="ftco-section-no-padding bg-light">
				<div class="hero-wrap">
					<div class="overlay"></div>
					<div class="d-flex">
						<div class="author-image text img p-md-5" style="background-image: url({{ company.image1.url }});">
							
						</div>
						<div class="author-info text p-4 p-md-5 mt-5 mb-5">
							<div class="desc">
								<span class="subheading">Nice To Meet You</span>
								<h1 class="big-letter">{{ company.name }}</h1>
								<h1 class="mb-4"><span>Who we Are </span></h1>
								 <p class="mb-4" style="text-indent: 50px;text-align: justify;">{{ company.description2 }}</p>
								<h3 class="signature h1">{{ company.name }}</h3>
								<ul class="ftco-social mt-3">
		              {% comment %} <li class="ftco-animate">
                  <a href="{{ user.profile.youtube_link }}"><span class="icon-youtube"></span></a>
                </li> {% endcomment %}
                <li class="ftco-animate">
                  <a href="{{ company.fb_link }}"><span class="icon-facebook"></span></a>
                </li>
                {% comment %} <li class="ftco-animate">
                  <a href="{{ user.profile.insta_link }}"><span class="icon-instagram"></span></a>
				  </li>
		            </ul> {% endcomment %}
	            </div>
						</div>
					</div>
				</div>
			</section>
			<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url(images/bg_1.jpg);">
	    	<div class="container">
	    		<div class="row justify-content-start">
	    			<div class="col-md-10">
			    		<div class="row">
			          <div class="col-xl-3 col-md-6 d-flex justify-content-center counter-wrap ftco-animate">
			            <div class="block-18">
			              <div class="text d-flex align-items-center">
			                <strong class="number" data-number="2">0</strong>
			                <span>Total season</span>
			              </div>
			            </div>
			          </div>
			          <div class="col-xl-3 col-md-6 d-flex justify-content-center counter-wrap ftco-animate">
			            <div class="block-18">
			              <div class="text d-flex align-items-center">
			                <strong class="number" data-number="50">0</strong>
			                <span>Participants</span>
			              </div>
			            </div>
			          </div>
			          {% comment %} <div class="col-xl-3 col-md-6 d-flex justify-content-center counter-wrap ftco-animate">
			            <div class="block-18">
			              <div class="text d-flex align-items-center">
			                <strong class="number" data-number="200">0</strong>
			                <span>Finished Photosessions</span>
			              </div>
			            </div>
			          </div>
			          <div class="col-xl-3 col-md-6 d-flex justify-content-center counter-wrap ftco-animate">
			            <div class="block-18">
			              <div class="text d-flex align-items-center">
			                <strong class="number" data-number="200">0</strong>
			                <span>Happy Clients</span>
			              </div>
			            </div>
			          </div> {% endcomment %}
			        </div>
		        </div>
	        </div>
	    	</div>
	    </section>


{% include 'footer.html' %}
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->

{% endblock %}
{% block javascript %}{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>{% block title %} {% endblock%}</title>
  <link
  href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700"
  rel="stylesheet"/>
<link
  href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700"
  rel="stylesheet"
/>
<link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet"/>

<link
  rel="stylesheet"
  href="{% static 'css/open-iconic-bootstrap.min.css' %}"
/>
<link rel="stylesheet" href="{% static 'css/animate.css' %}" />

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />

<link rel="stylesheet" href="{% static 'css/aos.css' %}" />

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" />

<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}" />
<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}" />

<link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

  {% block stylesheet %} {% endblock %}
</head>
<body>
  {% block body %} 
  {% block content %} {% endblock %} 
  {% endblock body %} 


<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block javascript %}  {% endblock %}
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}About me{% endblock %}
{% block stylesheet %} {% endblock%}

{% block content %}
{% include 'nav.html' %}

		<div id="colorlib-main">
			<section class="ftco-section ftco-bread">
				<div class="container">
					<div class="row no-gutters slider-text justify-content-center align-items-center">
	          <div class="col-md-8 ftco-animate">
	            <h1 class="bread">Contact</h1>
	          </div>
	        </div>
				</div>
			</section>
			<section class="ftco-section contact-section">
	      <div class="container">
	        <div class="row d-flex mb-5 contact-info">
	          <div class="col-md-12 mb-4">
	            <h2 class="h3 font-weight-bold">Contact Information</h2>
	          </div>
	          <div class="w-100"></div>
	          <div class="col-md-3 d-flex">
	          	<div class="info bg-light p-4">
		            <p><span>Address:</span> {{ company.address }} </p>
		          </div>
	          </div>
	          <div class="col-md-3 d-flex">
	          	<div class="info bg-light p-4">
		            <p><span>Phone:</span> <a href="tel://{{ company.phone_no }}">+977 {{ company.phone_no }}</a></p>
		          </div>
	          </div>
	          <div class="col-md-3 d-flex">
	          	<div class="info bg-light p-4">
		            <p><span>Facebook:</span> <a href="{{ company.fb_link }}">{{ company.fb_link }}</a></p>
		          </div>
	          </div>
	          <div class="col-md-3 d-flex">
	          	<div class="info bg-light p-4">
		            <p><span>Website</span> <a href="#">fplbhaktapur.herokuapp.com</a></p>
		          </div>
	          </div>
	        </div>
	        {% comment %} <div class="row block-9">
	          <div class="col-md-6 d-flex">
	            <form action="#" class="bg-light p-5 contact-form">
	              <div class="form-group">
	                <input type="text" class="form-control" placeholder="Your Name">
	              </div>
	              <div class="form-group">
	                <input type="text" class="form-control" placeholder="Your Email">
	              </div>
	              <div class="form-group">
	                <input type="text" class="form-control" placeholder="Subject">
	              </div>
	              <div class="form-group">
	                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
	              </div>
	              <div class="form-group">
	                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
	              </div>
	            </form>
	          
	          </div>

	          <div class="col-md-6 d-flex">
	          	<div id="map" class="bg-light"></div>
	          </div>
	        </div>
	      </div> {% endcomment %}
	    </section>

{% include 'footer.html' %}
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->

{% endblock %}
{% block javascript %}{% endblock %}

templates/footer.html

<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container px-md-5">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-4">
            {% comment %} <h2 class="ftco-heading-2">Previous Winner Voice</h2> {% endcomment %}
              
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="row">
        <div class="col-md-12">
          <p>
           
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This template is made with
            <i class="icon-heart" aria-hidden="true"></i> by
            <a href="https://colorlib.com" target="_blank">Aryan</a>
          
          </p>
        </div>
      </div> -->
    </div>
  </footer>

templates/gameweekwinner.html
 {% for obj in gwwinner %}
 {% if obj.name %}
 <div  class="gwwinner" style="background: rgb(0,36,33);
background: linear-gradient(180deg, rgba(0,36,33,1) 0%, rgba(0,255,149,1) 100%, rgba(0,255,115,0.7987570028011204) 100%);>
   <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-2 pb-3">
          <div
            class="col-md-7 heading-section heading-section-2 text-center ftco-animate"
          >
            <h2 class="mb-4" style="color:white; padding-top:30px;">Gameweek Winner : {{ obj.no }}</h2>
            <h1 class="mb-4">{{ obj.name }}</h2>
            <h2 class="mb-4">{{ obj.name.teamname }}</h2>
            <h2 class="mb-8" style:"float:right;">Points:{{ obj.points }}</h2>
          </div>
        </div>
        <div class="row no-gutters">
          
          
        
        </div>
      </div>
    </section>
</div>
              {% endif %}
          {% endfor %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Home{% endblock %}
{% block stylesheet %}

 {% endblock %} 

{% block content %}
{% include 'nav.html' %}

  <div id="colorlib-main">
    <section class="ftco-section-no-padding bg-light">
      <div class="hero-wrap">
        <div class="overlay"></div>
        <div class="d-flex align-items-center js-fullheight">
          <div class="author-image text img d-flex">
            <section class="home-slider js-fullheight owl-carousel">
              <div
                class="slider-item js-fullheight"
                style="background-image: url({{ company.logo.url }});"
              ></div>
              <div
                class="slider-item js-fullheight"
                style="background-image: url({{ company.image1.url }});"
              ></div>

              {% if company.image2.url %}
              <div
                class="slider-item js-fullheight"
                style="background-image:url({{ company.image2.url }});"
              ></div>
              {% endif %}


                <div
                class="slider-item js-fullheight"
                style="background-image: url({{ company.rewards.url }});"
              ></div>
            </section>
          </div>
          <div class="author-info text p-3 p-md-5">
            <div class="desc">
              {% comment %} <span class="subheading">Hello! I'm</span> {% endcomment %}
              <h1 class="big-letter">{{ company.name }}</h1>
              <h1 class="mb-4">
                {% comment %} <span>{{ user.get_full_name }}</span> {% endcomment %}
                {% comment %} <span style="color:#00c483;"> A {{ user.profile.occupation }}.</span> {% endcomment %}
                <span>{{ company.short_description }}</span>
              </h1>
              <p class="mb-4" style="text-indent: 50px;text-align: justify;">
                {{ company.description }}
              </p>
              <h3 class="signature h1">{{ company.name }}</h3>
              <ul class="ftco-social mt-3">
                {% comment %} <li class="ftco-animate"> {% endcomment %}
                  {% comment %} <a href="{{ user.profile.youtube_link }}"><span class="icon-youtube"></span></a> {% endcomment %}
                {% comment %} </li> {% endcomment %}
                <li class="ftco-animate">
                  <a href="{{ company.fb_link }}"><span class="icon-facebook"></span></a>
                </li>
                {% comment %} <li class="ftco-animate"> {% endcomment %}
                  {% comment %} <a href="{{ user.profile.insta_link }}"><span class="icon-instagram"></span></a> {% endcomment %}
                {% comment %} </li> {% endcomment %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
 
 {% include 'gameweekwinner.html' %}
 {% include 'winner.html' %}
   
    {% include 'footer.html' %}
  </div><!-- END COLORLIB-MAIN -->
</div><!-- END COLORLIB-PAGE -->


{% endblock %} 

{% block javascript %}{% endblock %}

templates/nav.html
<div id="colorlib-page">
    <a href="{% url 'cv:home' %}" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    <aside
      id="colorlib-aside"
      role="complementary"
      class="js-fullheight text-center"
    >
      <h1 id="colorlib-logo">
        <a href="{% url 'cv:home' %}"
        ><span class="img"
            style="background-image: url({{ company.logo.url }});"></span>
          {{ company.name }}
            </a>
      </h1>
      <nav id="colorlib-main-menu" role="navigation">
        <ul>
          <li class="colorlib-active"><a  href="{% url 'cv:home' %}">Home</a></li>
          <li><a  href="{% url 'cv:teams' %}">Teams</a></li>
          <li><a  href="{% url 'cv:about' %}">About Me</a></li>
          <li><a href="{% url 'cv:rewards' %}">Rewards</a></li>
          <li><a   href="{% url 'cv:contact' %}">Contact</a></li>
        </ul>
      </nav>
  
      {% comment %} <div class="colorlib-footer">
        <h3>Newsletter</h3>
        <div class="d-flex justify-content-center">
          <form action="#" class="colorlib-subscribe-form">
            <div class="form-group d-flex">
              <div class="icon"><span class="icon-paper-plane"></span></div>
              <input
                type="text"
                class="form-control"
                placeholder="Enter Email Address"
              />
            </div>
          </form>
        </div>
      </div> {% endcomment %}
    </aside>
    <!-- END COLORLIB-ASIDE -->

templates/rewards.html
{% extends 'base.html' %}
{% block title %}About me{% endblock %}
{% block stylesheet %} {% endblock%}

{% block content %}
{% include 'nav.html' %}

		<div id="colorlib-main">
			<section class="ftco-section ftco-bread">
				<div class="container">
					<div class="row no-gutters slider-text justify-content-center align-items-center">
	          <div class="col-md-8 ftco-animate">
	            <h1 class="bread">Season Rewards</h1>
	          </div>
	        </div>
				</div>
			</section>
 <section class="ftco-section instagram">
      <div class="container">

        <div class="row no-gutters">
          
          
          <div class="col-sm-12 col-md ftco-animate">
            <a
              href="{{ company.rewards.url }}"
              class="insta-img image-popup"
              style="background-image: url({{ company.rewards.url }});"
            >
            
              <div class="icon d-flex justify-content-center">
                {% comment %} <span class="icon-instagram align-self-center"></span> {% endcomment %}
              </div>
            </a>
          </div>
        
        </div>
      </div>
    </section>

{% include 'footer.html' %}
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->

{% endblock %}
{% block javascript %}{% endblock %}

templates/teams.html
{% extends 'base.html' %}
{% block title %} Teams {% endblock %}
{% block stylesheet %}
<style>
#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #00000;
  padding: 8px;
  color:black; !important
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #b8d6b9;
  color: white; !important
  
</style>
 {% endblock %} 

{% block content %}
{% include 'nav.html' %}

		<div id="colorlib-main">
			<section class="ftco-section ftco-bread">
				<div class="container">
					<div class="row no-gutters slider-text justify-content-center align-items-center">
	          <div class="col-md-8 ftco-animate">
	            <h1 class="bread">FPL Bhaktapur Teams</h1>
	          </div>
	        </div>
				</div>
			</section>
			<section class="ftco-section-3">
				
<table id="customers">
  <tr>
    <th>SN</th>
    <th>Team</th>
    <th>Manager</th>
  </tr>
  {% for team in teams%}
  <tr>
    <td>{{ team.id }}</td>
    <td>{{ team.teamname }}</td>
    <td>{{ team.name }}</td>
  </tr>
 {% endfor %}
</table>

			</section>

       {% for obj in winner %}
 {% if obj.name %}
 <div  class="gwwinner" style="background: rgb(0,36,33);
background: linear-gradient(0deg, rgba(0,36,33,1) 0%, rgba(0,255,149,1) 100%, rgba(0,255,115,0.7987570028011204) 100%);"

   <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-2 pb-3">
          <div
            class="col-md-7 heading-section heading-section-2 text-center ftco-animate"
          >
            <h2 class="mb-4" style="padding-top:30px;">{{ obj.Year }} Season Winner</h2>
            <h1 class="mb-4">{{ obj.name }}</h2>
            <h2 class="mb-8" style="color:white;">{{ obj.voice }}</h2>
          </div>
        </div>
        <div class="row no-gutters">
          
          
        
        </div>
      </div>
    </section>
</div>
              {% endif %}
          {% endfor %}
	 
			{% include 'footer.html' %}
			
		</div><!-- END COLORLIB-MAIN -->
	</div><!-- END COLORLIB-PAGE -->


	{% endblock %} 

	{% block javascript %}{% endblock %}

templates/winner.html
 {% for obj in winner %}
 {% if obj.name %}
   <section class="ftco-section instagram">
      <div class="container">
        <div class="row justify-content-center mb-2 pb-3">
          <div
            class="col-md-7 heading-section heading-section-2 text-center ftco-animate"
          >
            <h2 class="mb-4">{{ obj.Year }} Season Winner</h2>
            <h1 class="mb-4">{{ obj.name.name }}</h2>
          </div>
        </div>
        <div class="row no-gutters">
          
          
          <div class="col-sm-12 col-md ftco-animate">
            <a
              href="{{ obj.image.url }}"
              class="insta-img image-popup"
              style="background-image: url({{ obj.image.url }});"
            >
            
              <div class="icon d-flex justify-content-center">
                {% comment %} <span class="icon-instagram align-self-center"></span> {% endcomment %}
              </div>
            </a>
          </div>
        
        </div>
      </div>
    </section>

              {% endif %}
          {% endfor %}